apiVersion: v1
kind: Secret
metadata:
  name: postgresql
  namespace: db
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  POSTGRES_DB: "mydb"
  REPLICATION_USER: "postgres"
  REPLICATION_PASSWORD: "postgres"